import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect, useRef, MutableRefObject } from 'react';
import scrollama from 'scrollama';
import EyeLoading from '../components/eye-loading';
import InstructorCarousel from '../components/instructor-carousel';
import JobSelection from '../components/job-selection';
import TinderCards from '../components/tinder-cards';
import Welcome from '../components/welcome';

const Home: NextPage = () => {
  const sectionsContainer = useRef() as MutableRefObject<HTMLDivElement>;
  const [activeStep, setActiveStep] = useState(-1);
  useEffect(() => {
    scrollama()
      .setup({
        step: Array.from(sectionsContainer.current.children) as HTMLElement[],
        // debug: true,
        // offset: 0.5,
        // once: true,
      })
      .onStepEnter(({ index }) => {
        setActiveStep(index);
      });
    console.log(activeStep);
  }, [activeStep]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="gradient-bg bg-fixed" ref={sectionsContainer}>
        <Welcome />
        <JobSelection />
        <TinderCards />
        <EyeLoading />
        <InstructorCarousel />
        {/* <div className=" bg-emerald-100 w-screen h-screen">
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est
            aperiam porro laboriosam! Dicta tenetur velit hic ea impedit ad nam
            nesciunt porro voluptate. Molestiae aperiam suscipit aliquam,
            nesciunt aliquid consectetur?
          </p>
        </div>
        <div
          className={
            ' bg-emerald-100 w-screen h-screen' +
            (activeStep === 1 ? ' bg-yellow-100' : ' bg-black text-[#ffff]')
          }
        >
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est
            aperiam porro laboriosam! Dicta tenetur velit hic ea impedit ad nam
            nesciunt porro voluptate. Molestiae aperiam suscipit aliquam,
            nesciunt aliquid consectetur?
          </p>
        </div>
        <div className=" bg-emerald-100 w-screen h-screen">
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est
            aperiam porro laboriosam! Dicta tenetur velit hic ea impedit ad nam
            nesciunt porro voluptate. Molestiae aperiam suscipit aliquam,
            nesciunt aliquid consectetur?
          </p>
        </div> */}
      </main>
    </>
  );
};

export default Home;
